alter table QLNS_CAU_HOI add constraint FK_QLNS_CAU_HOI_ON_CHUYEN_NGANH foreign key (CHUYEN_NGANH_ID) references QLNS_CHUYEN_NGANH(ID);
create index IDX_QLNS_CAU_HOI_ON_CHUYEN_NGANH on QLNS_CAU_HOI (CHUYEN_NGANH_ID);
